
PROCURADOS = [
'ARQUIVO COBRANCAS',
'INSTR. COBRANCAS',
'RETORNO COBRANCAS',
'CONCILIACAO DDA',
'SISPAG',
'ARQUIVO PAGAMENTOS',
'RETORNO PAGAMENTOS',
'REL RETORNO CNAB',
'REL EXTRATO CNAB',
'REL RETORNO SISPAG',
]
